# Generated by Django 4.1.6 on 2023-04-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("tag", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tag",
                "managed": False,
            },
        ),
    ]
