# Generated by Django 4.1.6 on 2023-04-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP01", "0002_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Love",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.IntegerField()),
                ("love", models.CharField(max_length=99)),
                ("category", models.IntegerField()),
            ],
            options={
                "db_table": "love",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
